# create your drupal and postgres config here, based off the last assignment
services:
    drupal:
      image: custom-drupal
      build: .
      ports:
        - 8080:80
      volumes:
        - drupal-modules:/var/www/html/modules
        - drupal-profiles:/var/www/html/profiles
        - drupal-themes:/var/www/html/themes
        - drupal-sites:/var/www/html/sites
    db:
      image: postgres:14.3
      ports:
        - 5432
      environment:
        POSTGRES_PASSWORD: "pgdima"
        POSTGRES_DB: "drupal"
        POSTGRES_USER: "user"
      volumes:
        - drupal-data:/var/lib/postgresql/data

volumes:
    drupal-modules:
    drupal-profiles:
    drupal-themes:
    drupal-sites:
    drupal-data:

        